package modelo;
// Generated 20:57:28, 19 de xan. de 2023 by Hibernate Tools 5.6.14.Final

/**
 * Cicloformativo generated by hbm2java
 */
public class Ciclo implements java.io.Serializable {

	private Integer idCiclo;
	private String nombre;
	private Integer horas;

	public Ciclo() {
	}

	public Ciclo(String nombreCiclo, Integer horas) {
		this.nombre = nombreCiclo;
		this.horas = horas;
	}

	public Integer getIdCiclo() {
		return this.idCiclo;
	}

	public void setIdCiclo(Integer idCiclo) {
		this.idCiclo = idCiclo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombreCiclo) {
		this.nombre = nombreCiclo;
	}

	public Integer getHoras() {
		return this.horas;
	}

	public void setHoras(Integer horas) {
		this.horas = horas;
	}

	@Override
	public String toString() {
		return "Ciclo [idCiclo=" + idCiclo + ", nombre=" + nombre + ", horas=" + horas + "]";
	}

}
