package modelo;
// Generated 31 ene 2023 11:04:06 by Hibernate Tools 5.6.14.Final

/**
 * Direccion generated by hbm2java
 */
public class Direccion implements java.io.Serializable {

	private Integer id;
	@Override
	public String toString() {
		return "Direccion [id=" + id + ", calle=" + calle + ", numero=" + numero + ", poblacion=" + poblacion + "]";
	}

	private Provincia provincia;
	private String calle;
	private Integer numero;
	private String poblacion;

	public Direccion() {
	}

	public Direccion(Provincia provincia) {
		this.provincia = provincia;
	}

	public Direccion(Provincia provincia, String calle, Integer numero, String poblacion) {
		this.provincia = provincia;
		this.calle = calle;
		this.numero = numero;
		this.poblacion = poblacion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Provincia getProvincia() {
		return this.provincia;
	}

	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

}
