package modelo;
// Generated 31 ene 2023 11:04:06 by Hibernate Tools 5.6.14.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Modulo generated by hbm2java
 */
public class Modulo implements java.io.Serializable {

	@Override
	public String toString() {
		return "Modulo [idModulo=" + idModulo + ", nombre=" + nombre + "]";
	}

	private Integer idModulo;
	private String nombre;
	private Set profesors = new HashSet(0);

	public Modulo() {
	}

	public Modulo(String nombre) {
		this.nombre = nombre;
	}

	public Modulo(String nombre, Set profesors) {
		this.nombre = nombre;
		this.profesors = profesors;
	}

	public Integer getIdModulo() {
		return this.idModulo;
	}

	public void setIdModulo(Integer idModulo) {
		this.idModulo = idModulo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getProfesors() {
		return this.profesors;
	}

	public void setProfesors(Set profesors) {
		this.profesors = profesors;
	}

	public void addProfesor(Profesor profe) {

		getProfesors().add(profe);

		// conviene usar getProfesors() en lugar de this.profesors para forzar las
		// inicializaciones de los objetos proxy en caso de inicialización //lazy

		profe.getModulos().add(this);

	}

}
