package modelo;
// Generated 31 ene 2023 11:04:06 by Hibernate Tools 5.6.14.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia implements java.io.Serializable {

	private int idProvincia;
	private ComunidadAutonoma comunidadAutonoma;
	private String nombre;
	private Set direccions = new HashSet(0);

	public Provincia() {
	}

	public Provincia(int idProvincia, ComunidadAutonoma comunidadAutonoma, String nombre) {
		this.idProvincia = idProvincia;
		this.comunidadAutonoma = comunidadAutonoma;
		this.nombre = nombre;
	}

	public Provincia(int idProvincia, ComunidadAutonoma comunidadAutonoma, String nombre, Set direccions) {
		this.idProvincia = idProvincia;
		this.comunidadAutonoma = comunidadAutonoma;
		this.nombre = nombre;
		this.direccions = direccions;
	}

	public int getIdProvincia() {
		return this.idProvincia;
	}

	public void setIdProvincia(int idProvincia) {
		this.idProvincia = idProvincia;
	}

	public ComunidadAutonoma getComunidadAutonoma() {
		return this.comunidadAutonoma;
	}

	public void setComunidadAutonoma(ComunidadAutonoma comunidadAutonoma) {
		this.comunidadAutonoma = comunidadAutonoma;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getDireccions() {
		return this.direccions;
	}

	public void setDireccions(Set direccions) {
		this.direccions = direccions;
	}

}
